FROM resin/%%RESIN_MACHINE_NAME%%-python:2.7

MAINTAINER Gergely Imreh <gergely@resin.io>

ENV INITSYSTEM on

# Defines our working directory in container
WORKDIR /usr/src/app

# Copy requirements.txt first for better cache on later pushes
COPY ./requirements.txt /requirements.txt

RUN pip install -r /requirements.txt

# This will copy all source files to the working directory in the container
COPY . ./

# main.py will run when container starts up on the device
CMD ["bash", "start.sh"]
